spring:
  datasource:
    #添加并配置第三方数据库连接池Druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 300
      # 配置获取连接等待超时的时间
      max-wait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-connect-error-millis: 60000
#      #配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      # 配置一个连接在池中最大生存的时间，单位是毫秒
#      max-evictable-idle-time-millis: 1200000
    #mysql数据库连接
    url: jdbc:mysql://localhost:3306/kindergarten?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: pjj19991213

